#!/usr/bin/env bash
# Quick launcher for Zello examples

set -e

EXAMPLE=${1:-counter}

echo "Running example: $EXAMPLE"
echo ""

# Update main.zig to point to the example
cat > src/main.zig << MAIN
// Zello - Example launcher (auto-generated by run_example.sh)
const example = @import("examples/${EXAMPLE}.zig");

pub fn main() !void {
    try example.main();
}
MAIN

# Build and run
nix develop --impure --command bash -c "zig build run"
